#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LINKS="$CURRENT_DIR/links"

stay=1
path="$LINKS"

gen_cmd () {
	a=($(ls $path)) # Gets list of bookmarks
	lim=${#a[@]}
	i=0
	cmd=("NEWT_COLORS='root=,black
		border=green,black
		window=,black
		button=black,green
		actsellistbox=black,green
		listbox=green,black
		actlistbox=green,black
		textbox=green,black
		compactbutton=green,black'")

	cmd+=('whiptail'  '--menu "Select Bookmark!" 20 60 10')

	if [ ! $path -ef $LINKS ]; then
		cmd+=('".." "Back"')
	fi

	if [ -L "$path/.main" ]; then
		cmd+=("." "root")
	fi

	while [ $i -ne $lim ];
	do
		cmd+=("'$(($i+1))'")
		cmd+=("'${a[$i]}'")
		i=$(($i + 1))
	done

	cmd+=("3>&1 1>&2 2>&3")
}

run_cmd () {
	i=$(eval ${cmd[@]})
	if [ "$i" = "" ]; then
		cmd="!!"
	elif [ "$i" = ".." ]; then
		cmd="$path/.."
	elif [ "$i" = "." ]; then
		cmd="$path/.main"
	else
		i=$(($i - 1))
		cmd="$path/${a[$i]}" # Gets Selected File/Directory
	fi
}

if [ $# -eq 0 ]; then
	while [ $stay -eq 1 ]; do
		gen_cmd
		run_cmd

		if [ $cmd = "!!" ]; then
			echo "Exiting..."
			stay=0
		elif [ ! -L $cmd ] && [ -d $cmd ]; then
			path="$cmd"
		else
			stay=0
			eval "cd $(readlink -f $cmd)"
		fi
	done
elif [ "$1" = "add" ]; then
	eval "cd $LINKS"
elif [ "$1" = "r" ]; then
	eval "source ~/.bashrc"
else
	echo "Argument Given..Searching for link!"
	a="$(find $LINKS -name $1)"

	if [ -L $a ] && [ $(find $LINKS -name $1 | wc -l) -ne 0 ]; then
		echo "Link Found...Changing Directory!"
		eval "cd $(readlink -f $a)"
	else
		echo "LINK NOT FOUND!"
	fi
fi
